model:
  model_type: medium
  vocab_size: 10000
  context_length: 768
  d_model: 1024
  num_layers: 24
  num_heads: 16
  d_ff: 4096
  rope_theta: 10000

optimizer:
  lr: 0.001 
  betas: [0.9, 0.95]
  eps: 0.00000001
  weight_decay: 0.01

data:
  batch_size: 4

runtime:
  device: cuda
  use_mixed_precision: True
  profile_memory: False

benchmark:
  warmup_steps: 5
  measured_steps: 5
  mode: full_step # forward forward_backward full_step